#!/bin/sh
# shell script to prepend i3status with cmus song and artist

artist=$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)
song=$(cmus-remote -Q | grep title | cut -d ' ' -f3-)
echo "$artist - $song"
